#!/usr/bin/env 	zsh

DOWNLOADS="zip,python,ripgrep,gcc,stow,tmux,fzf"

for package in $(echo $DOWNLOADS | sed "s/,/ /g")
do
    echo "installing $package"
    apt install $folder -y
done

# install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# stow everything
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS="nvim,zsh,tmux,bin,vim"
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
