#!/usr/bin/env 	zsh

DOWNLOADS="git,zip,nodejs,npm,python,gcc,stow,tmux"

for package in $(echo $DOWNLOADS | sed "s/,/ /g")
do
    echo "installing $package"
    apt install $folder -y
done

# install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Install nvim
curl -Lo $HOME/nvim.appimage https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage 
chmod u+x $HOME/nvim.appimage
# $HOME/nvim.appimage
# Optional: exposing nvim globally.
sudo mv $HOME/squashfs-root /
sudo ln -s $HOME/squashfs-root/AppRun /usr/bin/nvim

# Install packer for nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# stow everything
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS="nvim,zsh,tmux"
fi

if [[ -z $DOTFILES ]]; then
	DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install


